name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm install -g @angular/cli@latest && npm install

      - name: Deploy
        run: ng deploy --base-href=https://andresparrar.github.io/dashboardAngular